# Generated by Django 2.2.1 on 2020-01-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
