# Generated by Django 2.2.1 on 2020-01-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_category_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='Categories',
        ),
    ]
