# Generated by Django 3.0.2 on 2020-01-25 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20200112_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_category',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
