# Generated by Django 3.0.2 on 2020-01-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200125_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='sub_category',
        ),
    ]
