# Generated by Django 3.0.2 on 2020-01-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_sub_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_categories',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
