# Generated by Django 3.0.2 on 2020-02-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('center_code', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.TextField()),
                ('Email', models.EmailField(max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('Password', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
