# Generated by Django 3.0.2 on 2020-02-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20200201_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='category',
        ),
    ]
