# Generated by Django 3.0.2 on 2020-02-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
