# Generated by Django 3.0.2 on 2020-02-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_student_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('exam_duration', models.DurationField(default='00:00:00')),
                ('pass_percentage', models.IntegerField()),
                ('reexam_date', models.DateField()),
                ('negative_marking', models.BooleanField(default=False)),
                ('tandc', models.TextField()),
                ('resultonmail', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_categories', to='login.Categories')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subcategories', to='login.sub_categories')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_subject', to='login.Subjects')),
            ],
        ),
    ]
