# Generated by Django 3.0.2 on 2020-02-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='admin',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='center',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
